<article class="addroom">

    <h1><?= (isset($user))?'Modifiy':'Add' ?> User </h1>
    <div class=" buttonadd">
        <a href="UserBack"> Cancel</a>
    </div>
    <p>
        <?php if (isset($_GET["error"])) : ?><?=$_GET["error"] ?>
        <?php else :?><?="" ?>
        <?php endif?>
    </p>
    <form
        action=" index.php?page=<?= (isset($user))?'ModifyUser&USERID='.htmlspecialchars($user['id_user']):'AddNewUser' ?>"
        method="post" enctype="multipart/form-data">
        <label for="id_role">User-Role</label>
        <select name="id_role" placeholder="id_role">
            <option value="<?= (isset($user)) ? htmlspecialchars($user['id_role'])  : "" ?>">
                <?= (isset($user)) ? htmlspecialchars($user['role'])  : "please select a role" ?></option>
            <?php foreach(  $this->roles as $role ): ?>
            <option value="<?=$role['id_role']?>"><?=$role['role']?></option>
            <?php endforeach ?>
        </select>
        <div>
            <label for="firstname">First-Name</label>
            <input type="text" id="firstname" name="firstname" placeholder="First-Name"
                value="<?=(isset($user['firstname'])) ? htmlspecialchars($user['firstname'])  : ""?>">
        </div>
        <div>
            <label for="lastname">Last-Name</label>
            <input type="text" id="lastname" name="lastname" placeholder="Last-Name"
                value="<?=(isset($user['lastname'])) ? htmlspecialchars($user['lastname'])  : ""?>">
        </div>
        <div>
            <label for="user_name">User-Name</label>
            <input type="text" id="user_name" name="user_name" placeholder="User-Name"
                value="<?=(isset($user['user_name'])) ? htmlspecialchars($user['user_name'])  : ""?>">
        </div>
        <?php if (!isset($user)) : ?>
        <div>
            <label for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="Password">
        </div>
        <div>
            <label for="passwordrepeat">Repeat Password</label>
            <input type="password" id="password" name="passwordrepeat" placeholder="Repeat Password ">
        </div>
        <?php endif?>
        <div>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="Email"
                value="<?=(isset($user['email'])) ? htmlspecialchars($user['email'])  : ""?>">
        </div>
        <div>
            <button class="button" type="submit" name="submit-user">Valider</button>
        </div>
    </form>
</article>