<article class="add-albums">
    <form action="AddNewAlbum" method="post" enctype="multipart/form-data">
        <h1>ADD-ALBUM</h1>
        <div class="error"> <?php if (isset($error)) : ?> <?=$error ;?>
            <?php  else : ?> <?=""?>
            <?php  endif ?>
        </div>
        <div>
            <label for="name">Album name</label>
            <input type="text" id="name" name="name" placeholder="Album-Name" value="">
        </div>
        <div class="btnload">
            <input type="button" class="uploadButton" value="Browse" />
            <input type="file" name="image" id="fileUpload" />
            <span class="fileName"> <i class="fas fa-cloud-upload-alt"></i> Select photos..</span>
        </div>
        <div class="submit">
            <button type="submit" name="submit-album">ADD-ALBUM</button>
            <a href="albums">Cancel</a>
        </div>
    </form>
</article>