<article class="booking">

    <form action="Bookroom" method="post">

        <h1><?= htmlspecialchars($room["room_name"]) ?></h1>
        <img class="big" src="<?=htmlspecialchars($room['src'])?>" alt="<?=htmlspecialchars($room['alt'])?>">
        <p><?= htmlspecialchars($room['descriptions']) ?></p>
        <p>Price per day</p>
        <p> <?= htmlspecialchars($room['price_perday']) ?> €</p>
        <input type="hidden" name="price"
            value="<?=(isset($room['price_perday'])) ? htmlspecialchars($room['price_perday'])  : ""?>" required>
        <input type="hidden" name="id_room"
            value="<?=(isset($room['id_room'])) ? htmlspecialchars($room['id_room'])  : ""?>" required>
        <div>
            <label for="email ">Customer Email</label>
            <input type="text" name="email" placeholder=""
                value="<?=(isset($_SESSION['email'])) ? htmlspecialchars($_SESSION['email'])  : ""?>" required>
            <input type="hidden" name="id" placeholder=""
                value="<?=(isset($_SESSION['id_client'])) ? htmlspecialchars($_SESSION['id_client'])  : ""?>" required>
        </div>
        <div>
            <label for="from_date">From</label>
            <input type="date" name="from_date" required>
        </div>

        <div>
            <label for="to_date">To</label>
            <input type="date" name="to_date" required>
        </div>
        <div>
            <label for="comments">Comments</label>
            <textarea name="comments" value="" rows="10" cols="30"></textarea>
        </div>
        <div class="submit">
            <button type="submit" name="submit-booking"> BOOK </button>
            <a href="rooms">Cancel </a>
        </div>
        <p class="errordate">
            <?php if (isset($_GET["error"])) : ?><?=$_GET["error"] ?>
            <?php else :?><?="" ?>
            <?php endif?>
        </p>

    </form>

</article>