<article class="login">
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Change password </h2>
            <div class="error"> <?php if (isset($error)) : ?> <?=$error ;?>
                <?php  else : ?> <?=""?>
                <?php  endif ?>
            </div>
            <!-- Icon -->
            <div class="fadeIn first">
                <img id="icon" src="assets/img/diving-logo.png" alt="logo">
            </div>
            <!-- Login Form -->
            <form action="UPdatePassword" method="post">
                <label for="oldpassword"></label>
                <input type="password" id="oldpassword" class="fadeIn third" name="oldpassword"
                    placeholder="OldPassword">
                <label for="NewPassword"></label>
                <input type="password" id="newpassword" class="fadeIn third" name="newpassword"
                    placeholder="NewPassword">
                <label for="rptpassword"></label>
                <input type="password" id="rptpassword" class="fadeIn third" name="rptpassword"
                    placeholder="NewPassword">
                <input type="submit" name="submit" class="fadeIn fourth" value="Change">
            </form>
            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="home">Cancel</a>
            </div>

        </div>
    </div>
</article>