<article class="customers">
    <h1>CUSTOMERS</h1>
    <p>
        <?php if (isset($_GET["error"])) : ?><?=$_GET["error"] ?>
        <?php else :?><?="" ?>
        <?php endif?>
    </p>
    <table>
        <thead>
            <tr>
                <th scope="col">ID Customer</th>
                <th scope="col">User Name</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th class="email" scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Zipcode</th>
                <th scope="col">Country</th>
                <th scope="col">Phone</th>
                <th scope="col" colspan="2">ACTION</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->customers as $customer): ?>
            <tr>
                <td data-label="ID Customer"><?=htmlspecialchars($customer['id_client'])?></td>
                <td data-label="User Name"><?=htmlspecialchars($customer['user_name'])?></td>
                <td data-label="First Name"><?=htmlspecialchars($customer['firstname'])?></td>
                <td data-label="Last Name"><?=htmlspecialchars($customer['lastname'])?></td>
                <td data-label="Email"><?=htmlspecialchars($customer['email'])?></td>
                <td data-label=" Address"><?=htmlspecialchars($customer['address'])?></td>
                <td data-label=" Zipcode"><?=htmlspecialchars($customer['zipcode'])?></td>
                <td data-label=" Country"><?=htmlspecialchars($customer['country'])?></td>
                <td data-label=" Phone"><?=htmlspecialchars($customer['phone'])?></td>
                <td data-label=" ACTION"><a class="delete button"
                        href="index.php?page=deleteCustomer&CUSTOMER=<?=htmlspecialchars($customer['id_client'])?>">
                        <i class="fas fa-trash-alt"></i> DELETE</a></td>
                <td data-label=" ACTION"><a
                        href="index.php?page=EditeCustomer&CUSTOMER=<?=htmlspecialchars($customer['id_client'])?>"
                        class="modify button"> <i class="fas fa-pencil-alt"></i> EDIT</a></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    </div>
</article>