<div class="dashboard">
    <h1>DASHBOARD WELCOME SCREEN</h1>
    <div class="dash">
        <div>
            <p> <i class="fas fa-user-alt"></i> CUSTOMERS No. : <span><?=count($this->customers)?></span></p>
        </div>
        <div>
            <p> <i class="fas fa-hotel"></i> BOOKINGS No. : <span><?=count($this->bookings)?></span></p>
        </div>
        <div>
            <p> <i class="fas fa-door-open"></i> ROOMS No. : <span><?=count($this->rooms)?></span></p>
        </div>
    </div>
</div>