<article class="diving">
    <h1>diving</h1>
    <section>
        <h2> Scuba Diving</h2>
        <img class="scubadiving" src="assets/img/scubadiving.jpg" alt="scubadiving">
        <p>Scuba diving is a mode of underwater diving where the diver uses a self-contained underwater breathing
            apparatus (scuba), which is completely independent of surface supply, to breathe underwater. Scuba divers
            carry their own source of breathing gas, usually compressed air, allowing them greater independence and
            freedom of movement than surface-supplied divers, and longer underwater endurance than breath-hold
            divers. Although the use of compressed air is common, a mixture of air and oxygen called enriched air or
            nitrox has become popular due to its benefit of reduced nitrogen intake during long or repetitive dives.
            Open circuit scuba systems discharge the breathing gas into the environment as it is exhaled, and consist of
            one or more diving cylinders containing breathing gas at high pressure which is supplied to the diver
            through a regulator. They may include additional cylinders for range extension, decompression gas or
            emergency breathing gas. Closed-circuit or semi-closed circuit rebreather scuba systems allow recycling
            of exhaled gases. The volume of gas used is reduced compared to that of open circuit, so a smaller cylinder
            or cylinders may be used for an equivalent dive duration. Rebreathers extend the time spent underwater
            compared to open circuit for the same gas consumption; they produce fewer bubbles and less noise than open
            circuit scuba which makes them attractive to covert military divers to avoid detection, scientific divers to
            avoid disturbing marine animals, and media divers to avoid bubble interference.
        </p>
        <p>Scuba diving may be done recreationally or professionally in a number of applications, including scientific,
            military and public safety roles, but most commercial diving uses surface-supplied diving equipment when
            this is practicable. Scuba divers engaged in armed forces covert operations may be referred to as frogmen,
            combat divers or attack swimmers</p>
        <p>A scuba diver primarily moves underwater by using fins attached to the feet, but external propulsion can be
            provided by a diver propulsion vehicle, or a sled pulled from the surface. Other equipment needed for
            scuba diving includes a mask to improve underwater vision, exposure protection (ie: a wet suit or dry suit),
            equipment to control buoyancy, a diving regulator to control the pressure of breathing gas for diving, and
            equipment related to the specific circumstances and purpose of the dive. Some scuba divers use a snorkel
            when swimming on the surface. Scuba divers are trained in the procedures and skills appropriate to their
            level of certification by instructors affiliated to the diver certification organisations which issue these
            certifications. These include standard operating procedures for using the equipment and dealing with the
            general hazards of the underwater environment, and emergency procedures for self-help and assistance of a
            similarly equipped diver experiencing problems. A minimum level of fitness and health is required by most
            training organisations, but a higher level of fitness may be appropriate for some applications. </p>
        <p><a href="https://en.wikipedia.org/wiki/Scuba_diving">source wikipedia</a> </p>

    </section>

    <section>
        <h2> Tec Diving </h2>
        <img class="techdiving" src="assets/img/techdiving.jpg" alt="techdiving">
        <p>Technical diving (also referred to as tec diving or tech diving) is scuba diving that exceeds the
            agency-specified limits of recreational diving for non-professional purposes. Technical diving may expose
            the diver to hazards beyond those normally associated with recreational diving, and to a greater risk of
            serious injury or death. The risk may be reduced by appropriate skills, knowledge and experience, and by
            using suitable equipment and procedures. The skills may be developed through appropriate specialised
            training and experience. The equipment often involves breathing gases other than air or standard nitrox
            mixtures, and multiple gas sources.

            The term technical diving has been credited to Michael Menduno, who was editor of the (now defunct) diving
            magazine aquaCorps Journal. The concept and term, technical diving, are both relatively recent
            advents, although divers have been engaging in what is now commonly referred to as technical diving
            for decades.
        </p>

        <p><a href="https://en.wikipedia.org/wiki/Technical_diving">source wikipedia</a> </p>

    </section>

    <section>
        <h2> Free Diving </h2>
        <img class="freediving" src="assets/img/freediving.jpg" alt="freediving">
        <p>Freediving, free-diving, free diving, breath-hold diving, or skin diving is a form of underwater diving that
            relies on breath-holding until resurfacing rather than the use of breathing apparatus such as scuba gear.

            Besides the limits of breath-hold, immersion in water and exposure to high ambient pressure also have
            physiological effects that limit the depths and duration possible in freediving.

            Examples of freediving activities are traditional fishing techniques, competitive and non-competitive
            freediving, competitive and non-competitive spearfishing and freediving photography, synchronised swimming,
            underwater football, underwater rugby, underwater hockey, underwater target shooting and snorkeling. There
            are also a range of "competitive apnea" disciplines; in which competitors attempt to attain great depths,
            times, or distances on a single breath.

            Historically, the term free diving was also used to refer to scuba diving, due to the freedom of movement
            compared with surface supplied diving.
        </p>
        <p>In ancient times freediving without the aid of mechanical devices was the only possibility, with the
            exception of the occasional use of reeds and leather breathing bladders.[4] The divers faced the same
            problems as divers today, such as decompression sickness and blacking out during a breath hold. Freediving
            was practiced in ancient cultures to gather food, harvest resources such as sponge and pearl, reclaim sunken
            valuables, and to help aid military campaigns.

            In Ancient Greece, both Plato and Homer mention the sponge as being used for bathing. The island of Kalymnos
            was a main centre of diving for sponges. By using weights (skandalopetra) of as much as 15 kilograms (33 lb)
            to speed the descent, breath-holding divers would descend to depths up to 30 metres (98 ft) to collect
            sponges. Harvesting of red coral was also done by divers.

            The Mediterranean had large amounts of maritime trade. As a result of shipwrecks, particularly in the fierce
            winter storms, divers were often hired to salvage whatever they could from the seabed. Divers would swim
            down to the wreck and choose the most valuable pieces to salvage.

            Divers were also used in warfare. Defenses against sea vessels were often created, such as underwater
            barricades, and hence divers were often used to scout out the seabed when ships were approaching an enemy
            harbor. If barricades were found, it was divers who were used to disassemble them, if possible.</p>

        <p><a href="https://en.wikipedia.org/wiki/Freediving">source wikipedia</a> </p>
    </section>





</article>