<article class="addroom">

    <h1><?= (isset($customer))?'Modifiy':'Add' ?> CUSTOMER </h1>
    <div class=" buttonadd">
        <a href="CustomersBack"> Cancel</a>
    </div>
    <?php if (isset($_GET["error"])) : ?><?=$_GET["error"] ?>
    <?php else :?><?="" ?>
    <?php endif?>








    <form
        action=" index.php?page=<?= (isset($customer))?'ModifyCustomerData&CUSTOMER='.htmlspecialchars($customer['id_client']):'AddcustomerDbase' ?>"
        method="post" enctype="multipart/form-data">

        <div class="customer"> User-Name :
            <?= (isset($customer)) ? htmlspecialchars($customer['user_name'])  : "" ?>
        </div>
        <div class="customer"> EMAIL :
            <?= (isset($customer)) ? htmlspecialchars($customer['email'])  : "" ?>
        </div>
        <div>
            <label for="address"> Address </label>
            <input type="text" id="address" name="address" placeholder="address"
                value="<?= (isset($customer)) ? htmlspecialchars($customer['address'])  : "" ?>">
        </div>
        <div>
            <label for="zipcode">Zipcode</label>
            <input type="text" id="zipcode" name="zipcode" placeholder="zipcode"
                value="<?= (isset($customer)) ? htmlspecialchars($customer['zipcode'])  : "" ?>">
        </div>
        <div>
            <label for="country">Country</label>
            <input type="text" id="country" name="country" placeholder="country"
                value="<?= (isset($customer)) ? htmlspecialchars($customer['country'])  : "" ?>">
        </div>
        <div>
            <label for="phone">Phone</label>
            <input type="text" id="phone" name="phone" placeholder="phone"
                value="<?= (isset($customer)) ? htmlspecialchars($customer['phone'])  : "" ?>">
        </div>
        <div>
            <button class="button" type="submit" name="submit-customer">Valider</button>
        </div>
    </form>



</article>