<article class="register">






    <form action="AddUser" method="post">

        <h1>REGISTER</h1>

        <div class="error"> <?php if (isset($error)) : ?> <?=$error ;?>
            <?php  else : ?> <?=""?>
            <?php  endif ?>
        </div>

        <div>
            <label for="user_name">User Name</label>
            <input type="text" id="user_name" name="user_name" placeholder="Username" value="">
        </div>
        <div>
            <label for="firstname">First Name</label>
            <input type="text" id="firstname" name="firstname" placeholder="FirstName" value="">
        </div>
        <div>
            <label for="lasttname">Last Name</label>
            <input type="text" id="lastname" name="lastname" placeholder="LastName" value="">
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="Password" value="">
        </div>
        <div>
            <label for="passwordrepeat">Repeat Password</label>
            <input type="password" id="password" name="passwordrepeat" placeholder="Repeat Password " value="">
        </div>
        <div>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="Email" value="">
        </div>
        <div>
            <label for="address"> Address </label>
            <textarea id="address" name="address" placeholder="Address"></textarea>
        </div>
        <div>
            <label for="zipcode">Zipcode</label>
            <input type="text" id="zipcode" name="zipcode" placeholder="Zipcode" value="">
        </div>
        <div>
            <label for="country">Country</label>
            <input type="text" id="country" name="country" placeholder="Country" value="">
        </div>
        <div>
            <label for="phone">Phone</label>
            <input type="text" id="phone" name="phone" placeholder="Phone" value="">
        </div>

        <div class="submit">
            <button type="submit" name="submit">Valider</button>
            <a href="home">Cancel</a>
        </div>
    </form>


</article>