<article class="login">
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Reset your password </h2>
            <div class="error"> <?php if (isset($error)) : ?> <?=$error ;?>
                <?php  else : ?> <?=""?>
                <?php  endif ?>
            </div>
            <!-- Icon -->
            <div class="fadeIn first">
                <img id="icon" src="assets/img/diving-logo.png" alt="logo">
            </div>

            <!-- Login Form -->
            <form action="SendResetEmail" method="post">
                <h3>An e-mail will be send to reset your password</h3>
                <label for="email">
                </label>
                <input type="email" id="email" class="fadeIn third" name="email" placeholder="Enter you e-mail adress">
                <input type="submit" name="submit-reset" class="fadeIn fourth" value="RECEIVE NEWPASSWORD BY MAIL">
            </form>
        </div>
    </div>
</article>