<div class="rooms">

    <h1>ROOMS</h1>
    <div class=" buttonadd">
        <a href="index.php?page=ShowAddRoomPage"> <i class="fas fa-plus"></i> Add Room</a>
    </div>
    <p>
        <?php if (isset($_GET["error"])) : ?><?=$_GET["error"] ?>
        <?php else :?><?="" ?>
        <?php endif?>
        <?php if (isset($success)) : ?><?= $success ?>
        <?php else :?><?="" ?>
        <?php endif?>
    </p>
    <div class="over">
        <table>
            <thead>
                <tr>
                    <th scope="col">ID ROOM</th>
                    <th scope="col">STATUS</th>
                    <th scope="col">NUMBER</th>
                    <th scope="col">NAME</th>
                    <th scope="col">PRICE</th>
                    <th scope="col">TAX</th>
                    <th scope="col" colspan="2">ACTION</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->rooms as $room): ?>
                <tr>
                    <td data-label="ID ROOM"><?=htmlspecialchars($room['id_room'])?></td>
                    <td data-label="STATUS"><?=htmlspecialchars($room['status'])?></td>
                    <td data-label="NUMBER"><?=htmlspecialchars($room['room_number'])?></td>
                    <td data-label="NAME"><?=htmlspecialchars($room['room_name'])?></td>
                    <td data-label="PRICE"><?=htmlspecialchars($room['price_perday'])?></td>
                    <td data-label="TAX"><?=htmlspecialchars($room['tax'])?></td>
                    <td data-label="ACTION"><a class="delete button"
                            href="index.php?page=deleteRoom&ROOM=<?=htmlspecialchars($room['id_room'])?>">
                            <i class="fas fa-trash-alt"></i> DELETE</a></td>
                    <td data-label="ACTION"><a
                            href="index.php?page=ModifyRoom&ROOM=<?=htmlspecialchars($room['id_room'])?>"
                            class="modify button"> <i class="fas fa-pencil-alt"></i> EDIT</a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>